openapi: 3.0.1
info:
  title: Todoist MCP Connector
  version: "1.0"
paths:
  /search:
    get:
      summary: Search Todoist tasks
      parameters:
        - name: query
          in: query
          required: true
          schema: { type: string }
      responses:
        '200':
          description: List of matching tasks
  /fetch:
    get:
      summary: Fetch a task by ID
      parameters:
        - name: id
          in: query
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Full task detail